platform :ios, '7.0' 
pod 'AFNetworking', '~> 2.4.0'
pod 'FontAwesome', '~> 4.3'
pod 'SDWebImage', '~>3.7'
pod 'FontAwesomeIconFactory', '~> 2.1'
pod 'Masonry', '~> 1.0'
pod 'MJExtension', '~> 3.0'
pod 'MJRefresh', '~> 3.1'
pod 'SVProgressHUD', '~> 2.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'TYAlertController', '~> 1.1.6'
pod 'SDCycleScrollView', '~> 1.65'
pod 'AnimatedGIFImageSerialization', '~> 0.2'
pod 'PNChart', '~> 0.8'
pod 'NullSafe', '~> 1.2'
pod 'UICountingLabel', '~> 1.2'
pod 'WebViewJavascriptBridge', '~> 5.0'
